### ISSUE TITLE
nginx1.21.6版本编译发现了报错

### ISSUE THREAD

**Issue by lsjhxl** [jntass/TASSL-1.1.1#2]
![lanxin_20221229181554](https://user-images.githubusercontent.com/16043562/209937163-7d2a5021-10ac-4b4b-ba25-691783f7cc2a.png)

**Comment by jntass** [comment]
为什么要去掉auto/lib/openssl/conf里面的.openssl目录

**Comment by lsjhxl** [comment]
编译Gmssl带过来，，忘了删了。。
