### ISSUE TITLE
nginx_tassl开启双向国密ssl验证

### ISSUE THREAD

**Issue by liujhjack** [jntass/TASSL-1.1.1#21]
使用nginx1.23.2版本，tassl编译后，配置国密ssl证书，并开启双向验证，客户端浏览器使用红莲花和360安全浏览器，访问后读取ukey证书，输入pin码访问，出现证书错误。
服务端的nginx日志：
2023/07/12 16:02:59 [info] 88327#88327: *110 SSL_do_handshake() failed (SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking, client: 10.123.10.184, server: 0.0.0.0:443
2023/07/12 16:02:59 [info] 88328#88328: *111 SSL_do_handshake() failed (SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking, client: 10.123.10.184, server: 0.0.0.0:443
2023/07/12 16:02:59 [info] 88328#88328: *112 SSL_do_handshake() failed (SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking, client: 10.123.10.184, server: 0.0.0.0:443
2023/07/12 16:02:59 [info] 88328#88328: *113 client SSL certificate verify error: (26:unsupported certificate purpose) while reading client request headers, client: 10.123.10.184, server: , request: "GET / HTTP/1.1", host: "10.123.10.181"
2023/07/12 16:02:59 [info] 88328#88328: *114 SSL_do_handshake() failed (SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking, client: 10.123.10.184, server: 0.0.0.0:443
2023/07/12 16:02:59 [info] 88328#88328: *115 client SSL certificate verify error: (26:unsupported certificate purpose) while reading client request headers, client: 10.123.10.184, server: , request: "GET /favicon.ico HTTP/1.1", host: "10.123.10.181", referrer: "https://10.123.10.181/"

国密浏览器页面显示：
400 Bad Request
The SSL certificate error

nginx配置：
server {
    listen       443 ssl;
    listen       [::]:443 ssl ipv6only=on;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:AES128-SHA:DES-CBC3-SHA:ECC-SM4-SM3:ECDHE-SM4-SM3:SM2-WITH-SMS4-SM3:ECDHE-SM2-WITH-SMS4-GCM-SM3;
    ssl_prefer_server_ciphers on;

    ######-----SM2------#####
    ssl_certificate /opt/tassl/tassl_demo/cert/certs/SS.crt;
    ssl_certificate_key /opt/tassl/tassl_demo/cert/certs/SS.key;

    ssl_certificate /opt/tassl/tassl_demo/cert/certs/SE.crt;
    ssl_certificate_key /opt/tassl/tassl_demo/cert/certs/SE.key;
    ######-----SM2------#####
 
    ssl_verify_client on;
    ssl_client_certificate /root/root_ca.crt;

    location / {
    
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://10.123.11.235:12345;
    
    }
}

**Comment by liujhjack** [comment]
抓包内容：
![image](https://github.com/jntass/TASSL-1.1.1/assets/48239364/325457aa-9527-4aee-90df-e8e2c881429d)

**Comment by zzl360** [comment]
先使用key里的签名证书和服务端配置的ca证书是否能给验证证书链。

**Comment by liujhjack** [comment]
目前使用阿里的tengine+tongsuo。一样的根证书配置+ukey，使用360企业安全浏览器和红莲花安全浏览器都是可以使用国密双向认证。总结:tassl的使用浙江CA的ueky国密双向认证不行，云南ca的ukey国密双向认证可以。tengine+tongsuo的浙江CA和云南CA国密双向认证都可以

**Comment by zzl360** [comment]
@liujhjack 是使用根证书验证的ukey里的签名证书么？

**Comment by liujhjack** [comment]
> 

是签名证书，对弹出输入pin码的框了，输入正确的后报页面是报的The SSL certificate error。抓包和nginx的日志如上。tengine+tongsuo是正常的打开页面了

**Comment by liujhjack** [comment]
> [zzl360](/zzl360)

我这边目前就是这样的情况。nginx的版本是1.23.2
