### ISSUE TITLE
目前状态下的tassl 和 阿里的 tongsuo 在国密协议实现上有什么区别吗？

### ISSUE THREAD

**Issue by muryliang** [jntass/TASSL-1.1.1#5]
据我了解现在两者都实现了  tls1.3 以及 国密双证功能， ssl 部分的国密协议都是支持
ciphersuite 方面，我比对了一下，tongsuo 和tassl的国密套件命名上有些区别，tongsuo的ecc和ecdhe以及gcm套件多了SM2字段， 还有就是多了rsa与国密算法的组合， 我想知道在国密方面两家现在有无不兼容的地方？
--- tongsuo  
+++ tassl  
@@ -36,10 +36,8 @@
 DHE-PSK-AES128-GCM-SHA256
 AES128-GCM-SHA256
 PSK-AES128-GCM-SHA256
-ECC-SM2-SM4-GCM-SM3
-ECDHE-SM2-SM4-GCM-SM3
-RSA-SM4-GCM-SHA256
-RSA-SM4-GCM-SM3
+ECC-SM4-GCM-SM3
+ECDHE-SM4-GCM-SM3
 AES256-SHA256
 AES128-SHA256
 ECDHE-PSK-AES256-CBC-SHA384
@@ -61,10 +59,8 @@
 DHE-PSK-AES128-CBC-SHA256
 RSA-PSK-AES128-CBC-SHA
 DHE-PSK-AES128-CBC-SHA
-ECC-SM2-SM4-CBC-SM3
-ECDHE-SM2-SM4-CBC-SM3
+ECC-SM4-SM3
+ECDHE-SM4-SM3
 AES128-SHA
-RSA-SM4-CBC-SHA256
-RSA-SM4-CBC-SM3
 PSK-AES128-CBC-SHA256
 PSK-AES128-CBC-SHA

**Comment by zzl360** [comment]
命名只是显示的问题，在握手的时候，都是以uint16_t的方式传的。

**Comment by Fury-Fox** [comment]
ecc_sm4_sm3方式 tassl连tongsuo失败。谁能给分析下吗？
