### ISSUE TITLE
配置RSA证书后，ip访问后，错误，域名访问没问题

### ISSUE THREAD

**Issue by liujhjack** [jntass/TASSL-1.1.1#8]
38 SSL_do_handshake() failed (SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking, client: 10.0.0.4, server: 0.0.0.0:8888

Wireshark抓包后，对比显示错误：TLSv1.2 Record Layer: Alert (Level: Fatal, Description: Certificate Unknown)

**Comment by zzl360** [comment]
有可能时证书链没有信任，可以设置忽略证书校验试试

**Comment by liujhjack** [comment]
ssl_verify_client off;
nginx配置
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers
ECDHE-RSA-AES128-GCM-SHA256:AES128-SHA:DES-CBC3-SHA:ECC-SM4-SM3:ECDHE-SM4-SM3:SM2-WITH-SMS4-SM3:ECDHE-SM2-WITH-SMS4-GCM-SM3;
        ssl_verify_client off;
        ssl_prefer_server_ciphers  on;
        ssl_certificate
/home/https_cert/E4CE297EB8A303D5EEB41FD07E6FBF2D.crt;
        ssl_certificate_key
/home/https_cert/E4CE297EB8A303D5EEB41FD07E6FBF2D.key;

zzl360 ***@***.***> 于2023年3月28日周二 12:13写道：

**Comment by yanshichao0226** [comment]
证书subject和subjectAltName是否只包含了域名，把IP地址也加进去试试

**Comment by liujhjack** [comment]
> 证书subject和subjectAltName是否只包含了域名，把IP地址也加进去试试
感谢提供方法，可能是doker swarm网络的原因，测试在宿主机是可以的，doker容器内才是这样的现象，我这边重新卸载再安装docker后，又可以了
